services:
  postgres:
    image: postgres
    restart: unless-stopped
    env_file:
      - .env.common
      - .env.postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: gemini_chat_bot
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_python_app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - my_network
networks:
  my_network:

volumes:
  pgdata:
    driver: local
